/**
 * JS Tag v3.4.3 (Thu Sep 26 15:49:41 UTC 2019)
 * RevJet
 * http://www.revjet.com/
 */
(function(){var g,h="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},k;if("function"==typeof Object.setPrototypeOf)k=Object.setPrototypeOf;else{var m;a:{var n={S:!0},p={};try{p.__proto__=n;m=p.S;break a}catch(a){}m=!1}k=m?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var q=k;function r(a,b,c){if("string"==typeof b)a.style[b]=c;else for(var e in b)a.style[e]=b[e]};function u(a){try{window.document.write(a)}catch(b){}}function v(a,b,c){c=void 0===c?window.document:c;a=c.createElement(a);for(var e in b.o)b.o.hasOwnProperty(e)&&a.setAttribute(e,b.o[e]);for(var d in b.style)b.style.hasOwnProperty(d)&&(a.style[d]=b.style[d]);return a}function w(a){var b={margin:0,padding:0,position:"relative",left:0,top:0,opacity:1,visibility:"visible",overflow:"hidden",border:"none",cssFloat:"none"};if(a)for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b}
function x(a){var b={allowtransparency:"false",frameborder:"0",hspace:"0",marginwidth:"0",marginheight:"0",scrolling:"no",vspace:"0"};if(a)for(var c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b}function y(a){a&&a.parentNode&&a.parentNode.removeChild(a)};function z(a,b,c){"undefined"!==typeof window.addEventListener?a.addEventListener(b,c,!1):a.attachEvent("on"+b,c)}function A(a,b,c){"undefined"!==typeof window.removeEventListener?a.removeEventListener(b,c,!1):a.detachEvent("on"+b,c)};function B(a){return a.replace(/<script[^>]*/ig,function(a){return a.replace(/(\s+)(type)(\s*=\s*)/ig,"$1data-revjet-script-type$3").replace(/(\s+)(language)(\s*=\s*)/ig,"$1data-revjet-script-language$3").replace(/(\s+)(src)(\s*=\s*)/ig,"$1data-revjet-script-src$3")+' type="text/revjet"'})}function C(a,b){var c=b.bind(this);a.addEventListener?a.addEventListener("load",c,!1):a.onreadystatechange=function(){if("loaded"===a.readyState||"complete"===a.readyState)a.onreadystatechange=null,c()}}
function D(a,b,c,e){return function(){if(0===b.length)e&&e();else{var d=b.shift(),f=D(a,b,c,e);if("SCRIPT"===d.nodeName&&"text/revjet"===d.type){var l=c.createElement("script");l.async=!1;var t=d.getAttribute("data-revjet-script-type");t&&(l.type=t);l.id=d.id;l.text=d.text||d.textContent||d.innerHTML||"";(t=d.getAttribute("data-revjet-script-language"))&&l.setAttribute("language",t);d.charset&&(l.charset=d.charset);if(d=d.getAttribute("data-revjet-script-src"))l.src=d;l.src&&C(l,f);a.insertBefore(l,
null);l.src||f()}else if(d.innerHTML&&0<=d.innerHTML.toLowerCase().indexOf("<script")){for(l=[];d.firstChild;)l.push(d.removeChild(d.firstChild));a.insertBefore(d,null);D(d,l,c,f)()}else a.insertBefore(d,null),f()}}};var E="undefined"!==typeof window.postMessage,F="undefined"!==typeof window.JSON&&"function"===typeof window.JSON.parse,G="undefined"!==typeof window?window:{};function H(a){a=a.split(".");for(var b=G,c;c=a.shift();)if(null!=b[c])b=b[c];else return null;return b};var I=null;function J(){this.c=H("extern")||H("$sf.ext");this.a=!1;this.f=[]}function K(a,b,c){if(a.c&&!a.a)try{$sf.ext.register(b,c,function(b,c){for(var d=a.f,e=0;e<d.length;e++)d[e](b,c)}),a.a=!0}catch(e){}};function L(a,b){this.g=a;this.a={};this.c=this.f=null;this.i=[];this.j=[];this.m=[];if(b&&b.c&&!this.f){var c=this.g.document.getElementById("REVJET_Tag-MESSAGING_FRAME");c?this.f=c:(this.f=v("iframe",{o:x({id:"REVJET_Tag-MESSAGING_FRAME"}),style:w({display:"none"})}),this.g.document.body.appendChild(this.f))}}
L.prototype.s=function(a,b,c){if(a.initialized){for(a=this.j.length-1;0<=a;a--)b=this.j[a],b.target===c&&(b.target.postMessage(JSON.stringify(b.message),"*"),this.j.splice(a,1));a:{for(a=0;a<this.i.length;a++)if(this.i[a]===c){a=!0;break a}a=!1}if(!a)for(this.i.push(c),a=this.m.length-1;0<=a;a--)b=this.m[a],b.aa===c&&b.code()}};
function M(a,b){a.c||(a.c=function(c){if(c&&"data"in c){var e=null;try{e=JSON.parse(c.data)}catch(f){}if(e&&"module"in e&&e.method&&"REVJET_Tag.Ad"===e.module){var d=b[e.method];d&&d.call(a,e.properties,e.messageId,c.source)}}},z(a.f?a.f.contentWindow:a.g,"message",a.c))}function N(a){a.c&&(A(a.g,"message",a.c),a.c=null)};var O=0;
function P(a,b,c){c=void 0===c?!1:c;var e=a.getSlotResponseObject();this.R=!!window.inDapIF;this.f=a;var d=window.parent;if(this.R&&window!==d){var f=this.f.getSlotObjectName();d[f]?O=++d[f].instanceNumber:(d[f]={},d[f].instanceNumber=++O)}else O++;this.M=b;this.L=e.content||"";this.P=e.failover_query_string;this.j=a.getAdWidth();this.s=a.getAdHeight();this.J=!1;this.u=window;I||(I=new J);this.G=I;K(this.G,this.j,this.s);if(this.c=c?null:new L(this.u,this.G))this.c.a.close=this.V.bind(this),this.c.a.collapse=
this.W.bind(this),this.c.a.expand=this.X.bind(this),this.c.a.relayAction=this.Z.bind(this),this.c.a.reload=this.$.bind(this),this.c.a.refresh=this.Y.bind(this)}g=P.prototype;g.V=function(a,b,c){this.D(c)&&this.f.destroy()};g.X=function(){};g.W=function(){};g.Z=function(){};g.$=function(a,b,c){this.D(c)&&this.f.reload()};g.Y=function(a,b,c){this.D(c)&&this.f.refresh()};g.D=function(){return!1};g.U=function(){return this.M};
function Q(a){var b=a.P;return b?'<!DOCTYPE html>\n<html>\n<head></head>\n<body style="background-color: #fff;">\n<iframe '+['src="'+((-1!==b.toString().indexOf("msgCode=1005")?R(a,"/~cdn/Ads/ad_shared/static/406.html"):R(a,"/~cdn/Ads/ad_shared/static/failover.html"))+"?"+b)+'"','allowtransparency="false" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"','width="'+a.j+'"','height="'+a.s+'"','style="border:0;vertical-align:bottom;width:'+a.j+"px;height:"+a.s+'px;"'].join(" ")+"></iframe>\n</body>\n</html>":
a.L}g.F=function(){if(this.c){var a=this.c;E&&F&&(a.a.setElementsInitialized=a.s.bind(a),M(a,a.a))}window.context&&window.context.reportRenderedEntityIdentifier&&window.context.reportRenderedEntityIdentifier(aa(this))};g.C=function(){this.c&&N(this.c)};g.B=function(){this.J=!0;if(this.c){var a=this.c;N(a);a.j=[];a.m=[];a.i=[]}this.G.f=[]};g.H=function(){return[]};g.T=function(){return this.J};function R(a,b){var c=a.f,e=c.getAdapter();return"https://"+c.getCdnDomainName()+(e?"/"+e:"")+b}
function aa(a){if(a=Q(a)){var b=/<title>([0-9]+)\/[0-9]+<\/title>/gi.exec(a);return b&&0<b.length?"revjet-"+b[1]:"revjet-S"+a.length}return"revjet-S0"}P.prototype.adDestroyed=P.prototype.T;P.prototype.getFrames=P.prototype.H;P.prototype.destroyAd=P.prototype.B;P.prototype.hideAd=P.prototype.C;P.prototype.showAd=P.prototype.F;P.prototype.getAdType=P.prototype.U;var ba=/<\/body>\s*<\/html>/i;function S(a,b,c){P.call(this,a,b,c);a=a.getSlotResponseObject();this.K=a.embd_tag_id;this.O=a.disable_iframe;this.N=a.deliveryWrapper;this.A=this.i=this.g=this.a=null;this.I=!!a.close_button;this.v=this.m=null}S.prototype=h(P.prototype);S.prototype.constructor=S;if(q)q(S,P);else for(var T in P)if("prototype"!=T)if(Object.defineProperties){var U=Object.getOwnPropertyDescriptor(P,T);U&&Object.defineProperty(S,T,U)}else S[T]=P[T];S.a=P.prototype;
function V(a,b){try{var c=a.contentDocument||a.contentWindow.document;c.open();c.write(b);c.close()}catch(e){}}function W(a){a=x({width:a.j,height:a.s,name:"revjet-single-iframe"});return v("iframe",{o:a,style:w()})}
function ca(a){if(!/loaded|complete/.test(window.document.readyState)){var b=a.f,c=Q(a);a.O||!ba.test(c)?u(c):(u('<ins id="'+b.getHolderId()+'"></ins>'),a.u.setTimeout(function(){var e=a.u.document.getElementById(b.getHolderId());a.i=e;r(e,w({width:a.j+"px",height:a.s+"px"}));var d=W(a);a.a=d;e.appendChild(d);V(d,c)},0))}}function X(a){a.I&&a.m&&(a.v=da(a),z(a.m,"click",a.v))}function Y(a){a.v&&a.m&&(A(a.m,"click",a.v),a.v=null)}g=S.prototype;
g.D=function(a){var b=this.a;return!(!b||b.contentWindow!==a)};
g.F=function(){P.prototype.F.call(this);if(this.g)r(this.g,"display","inline-block"),X(this);else{var a=this.f,b=this.u.document;if(a.getIsSyncLoading())ca(this);else{var c=this.K;if(this.f.isResponsive()&&c){var e=document.getElementById(c);if(e){var d={position:"absolute",display:"block",width:"100%",height:"100%",padding:"0",margin:"0",overflow:"hidden"};0===c.indexOf("revjet-tag")?r(e,d):this.A||(this.A=v("div",{o:{},style:d}),e.appendChild(this.A))}}if(c=Z(this))if(this.f.isResponsive()){if(this.a)r(c,
"display","block");else{b=x({name:"revjet-single-iframe"});this.a=b=v("iframe",{o:b,style:{display:"block",position:"absolute",top:"0",bottom:"0",left:"0",width:"100%",height:"100%",border:"0",padding:"0",margin:"0"}});var f=Q(this);c.appendChild(b);V(b,f)}X(this)}else if(e=b.getElementById(a.getWrapperId()),d=b.getElementById(a.getHolderId()),"div"===this.N){e&&(y(e),this.a=this.i=this.g=null);a=Q(this);if(a){f=b.createElement("div");f.innerHTML="L<div>"+B(a)+"</div>";a=[];for(f=f.lastChild;f.firstChild;)a.push(f.removeChild(f.firstChild));
f=a}else f=[];D(c,f,b)()}else{b=w({display:"inline-block",width:this.j+"px",height:this.s+"px"});e?(r(e,b),this.g=e):this.g=v("ins",{o:{id:a.getWrapperId()},style:b});b.display="block";d?(r(d,b),this.i=d):this.i=v("ins",{o:{id:a.getHolderId()},style:b});this.a=W(this);this.i.appendChild(this.a);this.I&&!this.m&&(b=R(this,"/~cdn/JS/03/3.4.3/x-button.28x28.png"),f=void 0===f?window.document:f,b=v("img",{o:{src:b},style:{margin:0,padding:0,position:"absolute",left:"auto",bottom:"auto",right:0,top:0,
border:0,zIndex:999999,width:"18px",height:"18px",cursor:"pointer",overflow:"hidden",cssFloat:"none",webkitAppearance:"none"}},f),r(b,{zIndex:989999,left:this.j-18+"px",right:"auto",pointerEvents:"auto"}),this.m=b,this.i.appendChild(b));if(!e||!d){for(this.g.appendChild(this.i);c.firstChild;)c.removeChild(c.firstChild);c.appendChild(this.g)}V(this.a,Q(this));X(this)}}}};function da(a){return function(){a.f.hide()}}
function Z(a){var b=a.f,c=a.u.document;b=a.K||b.getContainerId();return a.A||c.getElementById(b)}g.C=function(){P.prototype.C.call(this);Y(this);if(this.f.isResponsive()){var a=Z(this);r(a,"display","none")}else this.g&&r(this.g,"display","none")};g.B=function(){P.prototype.B.call(this);Y(this);if(this.f.isResponsive()){var a=Z(this);a&&y(a)}else this.a&&y(this.a);this.m=this.g=this.i=this.a=null};g.H=function(){return this.a?[this.a]:[]};S.prototype.getFrames=S.prototype.H;
S.prototype.destroyAd=S.prototype.B;S.prototype.hideAd=S.prototype.C;S.prototype.showAd=S.prototype.F;REVJET_Tag.ModuleManager.getInstance().setLoaded("banner",S);})();

