function Vulcan(){}Vulcan.dispatcher=new VulcanMessageDispatcher;Vulcan.prototype.launchApp=function(a,b,c){if(requiredParamsValid(a)){var d=new LaunchAppEvent;d.targetSpecifier=a;d.focus=b?"true":"false";d.cmdLine=void 0==c||null==c?"":c;Vulcan.dispatcher.dispatchEvent(d)}};Vulcan.prototype.isAppRunning=function(a){if(requiredParamsValid(a)){var b=new IsAppRunningEvent;b.targetSpecifier=a;Vulcan.dispatcher.dispatchEvent(b)}};
Vulcan.prototype.isAppInstalled=function(a){if(requiredParamsValid(a)){var b=new IsAppInstalledEvent;b.targetSpecifier=a;Vulcan.dispatcher.dispatchEvent(b)}};Vulcan.prototype.getAppPath=function(a){if(requiredParamsValid(a)){var b=new GetAppPathEvent;b.targetSpecifier=a;Vulcan.dispatcher.dispatchEvent(b)}};Vulcan.prototype.addEventListener=function(a,b){if(requiredParamsValid(a,b))return Vulcan.dispatcher.addEventListener(a,b)};
Vulcan.prototype.removeEventListener=function(a,b){requiredParamsValid(a,b)&&Vulcan.dispatcher.removeEventListener(a,b)};Vulcan.prototype.hasEventListener=function(a,b){if(requiredParamsValid(a,b))return null!=Vulcan.dispatcher.getEventListener(a,b)};Vulcan.prototype.dispatchEvent=function(a){requiredParamsValid(a)&&Vulcan.dispatcher.dispatchEvent(a)};var VulcanInterface=new Vulcan;function VulcanMessageDispatcher(){}VulcanMessageDispatcher.prototype.listeners=[];
VulcanMessageDispatcher.prototype.dispatchEvent=function(a){if(requiredParamsValid(a)){var b=new CSInterface,c=new CSEvent(a.type,a.scope,a.appId,a.extensionId);c.data=a.xmlData();b.dispatchEvent(c)}};VulcanMessageDispatcher.prototype.addEventListener=function(a,b){if(requiredParamsValid(a,b)){var c=new VulcanListener(a,b,this.listeners.length);this.listeners[c.seqID]=c;(new CSInterface).addEventListener(a,c.handler,c);return c}};
VulcanMessageDispatcher.prototype.removeEventListener=function(a,b){if(requiredParamsValid(a,b)){var c=this.getEventListener(a,b);null!=c&&((new CSInterface).removeEventListener(c.type,c.handler,c),this.listeners.splice(c.sepId,0))}};VulcanMessageDispatcher.prototype.getEventListener=function(a,b){for(var c=0;c<this.listeners.length;c++){var d=this.listeners[c];if(d.type==a&&d.callback==b)return d}return null};function VulcanListener(a,b,c){this.type=a;this.callback=b;this.seqID=c}
VulcanListener.prototype.handler=function(a){var b=null;switch(a.type){case LaunchAppEvent.TYPE:b=new LaunchAppEvent;break;case IsAppRunningEvent.TYPE:b=new IsAppRunningEvent;break;case IsAppInstalledEvent.TYPE:b=new IsAppInstalledEvent;break;case GetAppPathEvent.TYPE:b=new GetAppPathEvent;break;default:if(strStartsWith(a.type,SuiteMessageEvent.TYPE_PREFIX))b=new SuiteMessageEvent;else if(strStartsWith(a.type,HostMessageEvent.TYPE_PREFIX))b=new HostMessageEvent;else if(strStartsWith(a.type,VulcanMessageEvent.TYPE_PREFIX))b=
new VulcanMessageEvent;else return}b.initializeWithCSEvent(a);this.callback(b)};function VulcanMessageEvent(a){this.type=a;this.scope=VulcanMessageEvent.SCOPE_SUITE;this.appId=VulcanMessageEvent.DEFAULT_APP_ID;this.extensionId=VulcanMessageEvent.DEFAULT_EXTENSION_ID;this.data=""}VulcanMessageEvent.TYPE_PREFIX="vulcan.";VulcanMessageEvent.SCOPE_HOST="APPLICATION";VulcanMessageEvent.SCOPE_SUITE="GLOBAL";VulcanMessageEvent.DEFAULT_APP_ID="UNKNOWN";VulcanMessageEvent.DEFAULT_EXTENSION_ID="UNKNOWN";
VulcanMessageEvent.dataTemplate="<data>{0}</data>";VulcanMessageEvent.prototype.initializeWithCSEvent=function(a){this.type=a.type;this.scope=a.scope;this.appId=a.appId;this.extensionId=a.extensionId;this.data=a.data};VulcanMessageEvent.prototype.xmlData=function(){return this.data=String.format(VulcanMessageEvent.dataTemplate,"")};function LaunchAppEvent(){this.targetSpecifier="";this.focus="true";this.cmdLine="";this.result="true"}LaunchAppEvent.TYPE=VulcanMessageEvent.TYPE_PREFIX+"LaunchApp";
LaunchAppEvent.targetSpecifierTemplate="<targetSpecifier>{0}</targetSpecifier>";LaunchAppEvent.focusTemplate="<focus>{0}</focus>";LaunchAppEvent.cmdLineTemplate="<cmdLine>{0}</cmdLine>";LaunchAppEvent.resultTemplate="<result>{0}</result>";LaunchAppEvent.dataTemplate="<data>{0}</data>";LaunchAppEvent.prototype=new VulcanMessageEvent(LaunchAppEvent.TYPE);
LaunchAppEvent.prototype.xmlData=function(){var a=String.format(LaunchAppEvent.targetSpecifierTemplate,this.targetSpecifier),a=a+String.format(LaunchAppEvent.focusTemplate,this.focus),a=a+String.format(LaunchAppEvent.cmdLineTemplate,this.cmdLine),a=a+String.format(LaunchAppEvent.resultTemplate,this.result);return this.data=String.format(LaunchAppEvent.dataTemplate,a)};
LaunchAppEvent.prototype.initializeWithCSEvent=function(a){this.type=a.type;this.scope=a.scope;this.appId=a.appId;this.extensionId=a.extensionId;this.data=a.data;this.targetSpecifier=GetValueByKey(this.data,"targetSpecifier");this.focus=GetValueByKey(this.data,"focus");this.cmdLine=GetValueByKey(this.data,"cmdLine");this.result=GetValueByKey(this.data,"result")};
LaunchAppEvent.prototype.toString=function(){var a="type="+this.type,a=a+(", scope="+this.scope),a=a+(", appId="+this.appId),a=a+(", extensionId="+this.extensionId);return a+=", data="+this.xmlData()};function IsAppRunningEvent(){this.targetSpecifier="";this.result="true"}IsAppRunningEvent.TYPE=VulcanMessageEvent.TYPE_PREFIX+"IsAppRunning";IsAppRunningEvent.targetSpecifierTemplate="<targetSpecifier>{0}</targetSpecifier>";IsAppRunningEvent.resultTemplate="<result>{0}</result>";
IsAppRunningEvent.dataTemplate="<data>{0}</data>";IsAppRunningEvent.prototype=new VulcanMessageEvent(IsAppRunningEvent.TYPE);IsAppRunningEvent.prototype.xmlData=function(){var a=String.format(IsAppRunningEvent.targetSpecifierTemplate,this.targetSpecifier),a=a+String.format(IsAppRunningEvent.resultTemplate,this.result);return this.data=String.format(IsAppRunningEvent.dataTemplate,a)};
IsAppRunningEvent.prototype.initializeWithCSEvent=function(a){this.type=a.type;this.scope=a.scope;this.appId=a.appId;this.extensionId=a.extensionId;this.data=a.data;this.targetSpecifier=GetValueByKey(this.data,"targetSpecifier");this.result=GetValueByKey(this.data,"result")};IsAppRunningEvent.prototype.toString=function(){var a="type="+this.type,a=a+(", scope="+this.scope),a=a+(", appId="+this.appId),a=a+(", extensionId="+this.extensionId);return a+=", data="+this.xmlData()};
function IsAppInstalledEvent(){this.targetSpecifier="";this.result="true"}IsAppInstalledEvent.TYPE=VulcanMessageEvent.TYPE_PREFIX+"IsAppInstalled";IsAppInstalledEvent.targetSpecifierTemplate="<targetSpecifier>{0}</targetSpecifier>";IsAppInstalledEvent.resultTemplate="<result>{0}</result>";IsAppInstalledEvent.dataTemplate="<data>{0}</data>";IsAppInstalledEvent.prototype=new VulcanMessageEvent(IsAppInstalledEvent.TYPE);
IsAppInstalledEvent.prototype.xmlData=function(){var a=String.format(IsAppInstalledEvent.targetSpecifierTemplate,this.targetSpecifier),a=a+String.format(IsAppInstalledEvent.resultTemplate,this.result);return this.data=String.format(IsAppInstalledEvent.dataTemplate,a)};
IsAppInstalledEvent.prototype.initializeWithCSEvent=function(a){this.type=a.type;this.scope=a.scope;this.appId=a.appId;this.extensionId=a.extensionId;this.data=a.data;this.targetSpecifier=GetValueByKey(this.data,"targetSpecifier");this.result=GetValueByKey(this.data,"result")};IsAppInstalledEvent.prototype.toString=function(){var a="type="+this.type,a=a+(", scope="+this.scope),a=a+(", appId="+this.appId),a=a+(", extensionId="+this.extensionId);return a+=", data="+this.xmlData()};
function GetAppPathEvent(){this.targetSpecifier="";this.result="true"}GetAppPathEvent.TYPE=VulcanMessageEvent.TYPE_PREFIX+"GetAppPath";GetAppPathEvent.targetSpecifierTemplate="<targetSpecifier>{0}</targetSpecifier>";GetAppPathEvent.resultTemplate="<result>{0}</result>";GetAppPathEvent.dataTemplate="<data>{0}</data>";GetAppPathEvent.prototype=new VulcanMessageEvent(GetAppPathEvent.TYPE);
GetAppPathEvent.prototype.xmlData=function(){var a=String.format(GetAppPathEvent.targetSpecifierTemplate,this.targetSpecifier),a=a+String.format(GetAppPathEvent.resultTemplate,this.result);return this.data=String.format(GetAppPathEvent.dataTemplate,a)};
GetAppPathEvent.prototype.initializeWithCSEvent=function(a){this.type=a.type;this.scope=a.scope;this.appId=a.appId;this.extensionId=a.extensionId;this.data=a.data;this.targetSpecifier=GetValueByKey(this.data,"targetSpecifier");this.result=GetValueByKey(this.data,"result")};GetAppPathEvent.prototype.toString=function(){var a="type="+this.type,a=a+(", scope="+this.scope),a=a+(", appId="+this.appId),a=a+(", extensionId="+this.extensionId);return a+=", data="+this.xmlData()};
function SuiteMessageEvent(a){this.type=a;this.scope=VulcanMessageEvent.SCOPE_SUITE}SuiteMessageEvent.TYPE_PREFIX=VulcanMessageEvent.TYPE_PREFIX+"SuiteMessage.";SuiteMessageEvent.dataTemplate="<data>{0}</data>";SuiteMessageEvent.payloadTemplate="<payload>{0}</payload>";SuiteMessageEvent.prototype=new VulcanMessageEvent(SuiteMessageEvent.TYPE_PREFIX);SuiteMessageEvent.prototype.xmlData=function(){void 0==this.data&&(this.data=String.format(SuiteMessageEvent.dataTemplate,""));return this.data};
SuiteMessageEvent.prototype.initializeWithCSEvent=function(a){this.type=a.type;this.scope=a.scope;this.appId=a.appId;this.extensionId=a.extensionId;this.data=a.data};SuiteMessageEvent.prototype.setPayload=function(a){a=cep.encoding.convertion.utf8_to_b64(a);a=String.format(SuiteMessageEvent.payloadTemplate,a);this.data=String.format(SuiteMessageEvent.dataTemplate,a)};
SuiteMessageEvent.prototype.getPayload=function(){var a=GetValueByKey(this.data,"payload");return null!=a?cep.encoding.convertion.b64_to_utf8(a):null};SuiteMessageEvent.prototype.toString=function(){var a="type="+this.type,a=a+(", scope="+this.scope),a=a+(", appId="+this.appId),a=a+(", extensionId="+this.extensionId);return a+=", data="+this.xmlData()};function HostMessageEvent(a){this.type=a;this.scope=VulcanMessageEvent.SCOPE_HOST}HostMessageEvent.TYPE_PREFIX=VulcanMessageEvent.TYPE_PREFIX+"HostMessage.";
HostMessageEvent.dataTemplate="<data>{0}</data>";SuiteMessageEvent.payloadTemplate="<payload>{0}</payload>";HostMessageEvent.prototype=new VulcanMessageEvent(HostMessageEvent.TYPE_PREFIX);HostMessageEvent.prototype.xmlData=function(){void 0==this.data&&(this.data=String.format(HostMessageEvent.dataTemplate,""));return this.data};HostMessageEvent.prototype.initializeWithCSEvent=function(a){this.type=a.type;this.scope=a.scope;this.appId=a.appId;this.extensionId=a.extensionId;this.data=a.data};
HostMessageEvent.prototype.setPayload=function(a){a=cep.encoding.convertion.utf8_to_b64(a);a=String.format(HostMessageEvent.payloadTemplate,a);this.data=String.format(HostMessageEvent.dataTemplate,a)};HostMessageEvent.prototype.getPayload=function(){var a=GetValueByKey(this.data,"payload");return null!=a?cep.encoding.convertion.b64_to_utf8(a):null};
HostMessageEvent.prototype.toString=function(){var a="type="+this.type,a=a+(", scope="+this.scope),a=a+(", appId="+this.appId),a=a+(", extensionId="+this.extensionId);return a+=", data="+this.xmlData()};String.format=function(a){if(0==arguments.length)return null;var b=Array.prototype.slice.call(arguments,1);return a.replace(/\{(\d+)\}/g,function(a,d){return b[d]})};
function GetValueByKey(a,b){if(window.DOMParser){var c=new window.DOMParser;try{var d=c.parseFromString(a,"text/xml").getElementsByTagName(b)[0];if(d&&d.childNodes[0])return d.childNodes[0].nodeValue}catch(e){}}return""}function requiredParamsValid(){for(var a=0;a<arguments.length;a++){var b=arguments[a];if(void 0==b||null==b)return!1}return!0}function strStartsWith(a,b){return"string"!=typeof a?!1:0===a.indexOf(b)};
